### ISSUE TITLE
前后端wav音频传输问题

### ISSUE THREAD

**Issue by yangzejun0312** [lintaojlu/TalkTales#19]
1. 请见audio_fuck分支中的代码，前端参照interaction_new5.html，传送wav文件给后端的时候总是报错，前端录的音频下载后可以正常播放，在后端保存的音频也可以正常播放，但是就是音频传过去的时候就是播放不了，怎么解决

**Comment by lintaojlu** [comment]
html脚本缺失某种头文件或函数
